spring:
  quartz:
    properties:
      org.quartz.scheduler:
        instanceId: AUTO
  datasource:
    username: ***
    password: ***
    url: "jdbc:mysql://localhost:3306/deviceDb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8"
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: deviceDb